
directories:
  fastq_dir: "/home/luisagi/github/XfCapture/example_data"
  output_dir: "/home/luisagi/github/XfCaptureresults_example"

references:
  probes: /home/luisagi/github/XfCapture/reference_seqs/probes.fasta # non reduced probes sequences
  xf_genomes: /home/luisagi/github/XfCapture/reference_seqs/xf_genomes

kraken2:
  #database: /data/databases/k2_pluspfp_08gb_20250402 # Light 8GB database
  database: /data/databases/k2_pluspfp_16gb_20250402  # Recommended 16GB database
  threads: 16
  memory_mapping: false # Avoids loading database into RAM
  